name: Deploy to Minikube using GitHub Actions
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
      - uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@master

      - name: Try the Cluster
        run: kubectl get pods -A

      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t lathika/node-app:latest .
          echo "Verifying images:"
          docker images

      - name: Deploy to Minikube
        run: kubectl apply -f k8s-node-app.yaml

      - name: Verify Deployment
        run: |
          echo "Waiting for pods to be ready..."
          kubectl rollout status deployment/nodejs-app -n default
          kubectl get pods -n default

      - name: Verify Service
        run: |
          echo "Verifying service..."
          kubectl get svc nodejs-app -n default

      - name: Test Service URLs
        run: |
          echo "Listing all services in Minikube:"
          minikube service list
          echo "Fetching service URL for nodejs-app:"
          minikube service nodejs-app --url
