name: Deploy to Minikube using GitHub Actions

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 'latest'
          kubernetes-version: 'v1.24.0'
          driver: docker
          wait: true

      - name: Set up Docker environment
        run: eval $(minikube -p minikube docker-env)

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t lathika0325/node-app:latest .
          minikube image load lathika0325/node-app:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s-node-app.yaml
          kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=120s

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app-service --url
